### ISSUE TITLE
gh-pages not working

### ISSUE THREAD

**Issue by Jabher** [Legitcode/modal#10]

**Comment by RavenHursT** [comment]
I'm adding the obligatory :+1:

**Comment by zackify** [comment]
I briefly looked into this yesterday. Weird that it doesn't show up. I will
mess with it tonight. For now you can just pull down the gh-pages branch.

**Comment by zackify** [comment]
I contacted github, they triggered a manual page build, looks like something weird happened on their end.

**Comment by RavenHursT** [comment]
Why close this?  the Page is "there" now.. but there's no examples, nothing.  The link back to the project doesn't even work:

![screen shot 2016-04-13 at 2 19 26 pm](https://cloud.githubusercontent.com/assets/496983/14509767/e2ebf886-0182-11e6-8961-cd79b0bbbe74.png)

**Comment by zackify** [comment]
The only example there is clicking "open modal" I put this page together really fast in the past. I added an example for no fade in and a fade in. You can check it now. Hope that's enough for you. I'm debating rethinking this component or pointing people towards https://github.com/react-bootstrap/react-overlays

**Comment by RavenHursT** [comment]
Ok.. thanks @zackify
