### ISSUE TITLE
background scroll

### ISSUE THREAD

**Issue by ghost** [Legitcode/modal#11]
When user clicks to open, the background scrolls up. This is the exact same issue from react-modal that I was trying to avoid. I tried adding an overflowY: hidden property to the style object that I pass in with no luck. Is there any way to stop the scroll up and just keep the background position the same?

**Comment by zackify** [comment]
There's nothing in the code that triggers a scroll. Are you sure your window height isn't shrinking or something?

**Comment by ghost** [comment]
I'm not changing height at all. Just trying to prevent a scroll to top on
opening.

**Comment by ghost** [comment]
Do you set top anywhere? That could be it if it defaults to 0

**Comment by zackify** [comment]
You can see the source right here https://github.com/Legitcode/modal/blob/master/src/simple-modal.js. No scroll

**Comment by ghost** [comment]
It was my mistake. I had an <a> element with an href attribute set to "#". `<a href="#" />`. If you remove the href, it wont scroll. Leaving this here for anyone else that runs into this issue.
