### ISSUE TITLE
Not compatible with React 15

### ISSUE THREAD

**Issue by adrianso** [Legitcode/modal#12]
Just installed React 15 in my project.

When I run npm install, I got the following warning.
`npm WARN simple-react-modal@0.4.8 requires a peer of react@^0.14.3 but none was installed.`

**Comment by zackify** [comment]
I'll update this component tonight with the peer fix and possibly refactor since I haven't messed with it in a while

**Comment by zackify** [comment]
@adrianso try it now, should be okay. I don't have time today to refactor things though.

**Comment by adrianso** [comment]
@zackify Yup, I can confirm that npm install is no longer complaining.
