### ISSUE TITLE
Unknown prop warning

### ISSUE THREAD

**Issue by axelson** [Legitcode/modal#14]
Running with React 15.2.1 gives this warning:

> Warning: Unknown props `show`, `onClose`, `containerStyle`, `transitionSpeed` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

Looking through the code this happens because the `<Modal>` props are not filtered out of `{...this.props}` before passing them to the `<div>`.

**Comment by zackify** [comment]
Just merged a PR that fixes this.

**Comment by axelson** [comment]
Thanks! Works great.
