### ISSUE TITLE
ES5 and require

### ISSUE THREAD

**Issue by cdownard** [Legitcode/modal#2]
We're using require in our project. I'm not sure how to require the CSS class for this.

`var Modal = require('simple-react-modal');` works great but browserify blows up if i try to require the css as described. Obviously I'm doing it incorrectly. Is this a situation where just bringing the css file in directl is a better idea?

Thanks!

**Comment by zackify** [comment]
Thanks for making this issue. Right after making this I received a lot of great feedback and fixed a lot of things. The two things left are including styles by default, unless if you put in a custom class name. Should have that done asap (before tomorrow night). Then it will just work with default styles unless you place a classname on it.

**Comment by zackify** [comment]
I just updated it to `0.2.0` on npm. Not specifying a className will load the default styles. Let me know what you think @cdownard

**Comment by cdownard** [comment]
Just put it in by copying and pasting the css and then I'm overriding pieces of it. I love this so far. It's exactly what our project needed. Our designs call for modals that are pretty different contextually so I love this.

**Comment by zackify** [comment]
That's the exact same problem at my work! I advise updating it still, and the next version I push out will all be behind the scenes stuff that will correctly mark content behind it as hidden for screen readers and possibly a slight css change as to how it shows (using visibility) I'm glad someone else is using it!

**Comment by cdownard** [comment]
Yeah I'll update in the morning. If you're ever in Denver I owe you a beer. Come have lunch with the team cause you just saved us headache.

**Comment by zackify** [comment]
I've been to Boulder once, last year. Went to the red rock amphitheater. I'll try to remember that if I ever go back haha
