### ISSUE TITLE
simple-react-modal → react-simple-modal

### ISSUE THREAD

**Issue by imevro** [Legitcode/modal#4]
I propose change name to `react-simple-modal`.
`react` as namespace and `simple-modal` as component for react. Why not?

**Comment by zackify** [comment]
Is there even a way to do this without leaving people behind who have `simple-react-modal` in their package.json?

**Comment by imevro** [comment]
Maybe [deprecate](https://docs.npmjs.com/cli/deprecate)? Old package will live until you [unpublish](https://docs.npmjs.com/cli/unpublish) it.

**Comment by zackify** [comment]
I don't think there's a big enough reason to switch it, even though i do agree that's a better name.
