### ISSUE TITLE
Ability to add a class to the inner div

### ISSUE THREAD

**Issue by dphaener** [Legitcode/modal#5]
Should be able to add a class to the inner div, so you don't have to declare the inline styling.

**Comment by zackify** [comment]
Good idea I'll add it tonight

**Comment by dphaener** [comment]
And scrolling…..

**Comment by zackify** [comment]
By scrolling I'm assuming it should center even if the page is scrolled
down?

**Comment by zackify** [comment]
added in 0.4.6
